core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .forms import LoginForm
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index , name='index'),
    path("contact/" , views.contact, name='contact'),
    path("signup/" , views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_user ,name='logout')

]

item/urls.py
from django.urls import path

from . import views


app_name = 'item'

urlpatterns = [
    path('<int:pk>/' , views.detail , name='detail'),
    path('<int:pk>/delete/' , views.delete , name='delete'),
    path('<int:pk>/edit/' , views.edit , name='edit'),
    path('new/', views.new , name='new'),
    path('', views.items , name='items'),
    
]

main_folder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('item/', include('item.urls' )),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    # path('', views.index , name='index')
    # path('', views.index , name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# my name is asdddkmighplhfgghfty

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'your name',
        'class'       : 'w-full  py-4 px-6 rounded-xl bg-gray-200  focus:bg-gray-100 focus:shadow-[0_9px_9px_-4px_#3b71ca] focus:p-7 transition-all' 
        
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'your password',
        'class'       : 'w-full  py-4 px-6 rounded-xl bg-gray-200 focus:bg-gray-100 focus:shadow-[0_9px_9px_-4px_#3b71ca] focus:p-7 transition-all'
        
    }))
    


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1',  'password2')
        
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'your name',
        'class'       : 'w-full  py-4 px-6 rounded-xl bg-gray-200  focus:bg-gray-100 focus:shadow-[0_9px_9px_-4px_#3b71ca] focus:p-7 transition-all' 
        
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder' : 'email@',
        'class'       : 'w-full  py-4 px-6 rounded-xl bg-gray-200 focus:bg-gray-100 focus:shadow-[0_9px_9px_-4px_#3b71ca] focus:p-7 transition-all'
        
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'your password',
        'class'       : 'w-full  py-4 px-6 rounded-xl bg-gray-200 focus:bg-gray-100 focus:shadow-[0_9px_9px_-4px_#3b71ca] focus:p-7 transition-all'
        
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'confirm password',
        'class'       : 'w-full  py-4 px-6 rounded-xl bg-gray-200  focus:bg-gray-100 focus:shadow-[0_9px_9px_-4px_#3b71ca] focus:p-7 transition-all'
        
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import  Category, Item
from django.contrib.auth import logout
from django.contrib import messages

from .forms import SignupForm




def index(request):
    items = Item.objects.filter(is_sold=False)
    category = Category.objects.all()
    listt = {
        'category' : category,
        "items" :     items,
        
    }
    return render(request, 'core/index.html', listt)


def contact(request):
    return render(request, "core/contact.html")


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        
        if form.is_valid():

            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    a = {
        'form' : form
    }
    return render(request, 'core/signup.html',a)


def logout_user(request ):
    logout(request)
    messages.success(request, ("Loggedout succefully !"))
    return redirect('core:index')

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock title %}

{% block content %}
<div class='bg-teal-500 py-6 rounded-xl text-white'>
<h1 class='ml-6 '>
    Contact page
</h1> 
</div>
{% endblock content %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}

    <div class='mt-6 px-6 py-12  bg-gray-100 rounded-xl'>
        <h2 class='mb-12 text-2xl text-center '>
            Newest items
        </h2>   

        <div class='grid grid-cols-4  gap-4 '>
            {% for item in items %}
            
                <div class='shadow-[0_4px_9px_-4px_#3b71ca]'>
                    <a href="{% url 'item:detail' item.id %}" >
                        <div>
                            <img src="{{ item.image.url}}" class='rounded-t-xl'>
                        </div>
                        <div class='p-6 bg-white rounded-b-xl'>
                            <h2 class='text-2xl '>
                                {{ item.name}}
                            </h2>
                            <p  class='text-gray-500 '>
                                Price : {{ item.price}}
                            </p>
                            {% if request.user == item.created_by %}
                            <p  class='text-gray-500 '>
                                Created by you
                            </p>
                            {% endif %}
                        </div>
                    </a>
                </div>
                
                {% endfor %}
                
            </div>
        </div>
        <div class='mt-6 px-6 py-12  bg-gray-100 rounded-xl'>
            <h2 class='mb-12 text-2xl text-center '>
                Categories
            </h2>
    
            <div class='grid grid-cols-3  gap-3 '>
                {% for c in category %}
                    
                    <div>
                        <a href='#' >

                            <div class='p-6 bg-white rounded-b-xl'>
                                <h2 class='text-2xl '>
                                    {{ c.name}}
                                </h2>
                                <p  class='text-gray-500 '>
                                    {{c.items.count}} items
                                </p>
                            </div>
                        </a>
                    </div>
                    
                
                {% endfor %}
            </div>
        </div>
{% endblock content %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
Sign up
{% endblock title %}


{% block content %}
<div class='w-1/2 my-6 p-6 mx-auto bg-gray-300 rounded-xl shadow-[0_9px_9px_-4px_#3b71ca] '>
    <h1 class='mb-6 text-3xl'>Log in</h1>

    <form action="." method="post">
        {% csrf_token %}

        

        <div class="mb-3 ">
            <label for="" class="inline-block mb-2"> Username: </label><br>
            {{ form.username}}

        </div>



        <div class="mb-3 ">
            <label for="" class="inline-block mb-2"> Password: </label><br>
            {{ form.password}}

        </div>

        {% if form.errors or form.none_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                
            
            {{ field.errors}}
            
            {% if  field.errors  == '' %}
            dsff
            {% endif %} 
            {% endfor %}
                
                

            {{ form.none_field_errors }}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white transition-all shadow-[0_9px_9px_-4px_#3b71ca] "> Submet  </button>
        <a href="{% url 'core:signup' %}" class='py-4 px-8 bg-gray-500 text-lg text-white rounded-xl hover:bg-gray-700 shadow-[0_9px_9px_-4px_#3b71ca]  transition-all'> Sign up</a>
    </form>
    
</div>
{% endblock content %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
Sign up
{% endblock title %}


{% block content %}
<div class='w-1/2 my-6 p-6 mx-auto bg-gray-300 rounded-xl'>
    <h1 class='mb-6 text-3xl'>Sign up </h1>

    <form action="." method="post">
        {% csrf_token %}

        

        <div class="mb-3 ">
            <label for="" class="inline-block mb-2"> Username: </label><br>
            {{ form.username}}

        </div>

        <div class="mb-3 ">
            <label for="" class="inline-block mb-2">Email: </label><br>
            {{ form.email }}

        </div>

        <div class="mb-3 ">
            <label for="" class="inline-block mb-2"> Password: </label><br>
            {{ form.password1}}

        </div>
        <div class="mb-3 ">
            <label for="" class="inline-block mb-2"> Confirm Password: </label><br>
            {{ form.password2}}

        </div>
        {% if form.errors or form.none_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors}}
            {% endfor %}

            {{ form.none_field_errors }}
        </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"> Submet  </button>
    </form>
    
</div>
{% endblock content %}